services:
  jupyter1:
    restart: always
    build:
      context: .
    ports:
      - 8888:8888
    volumes:
      - ~/projects:/home/jovyan/projects
      - ~/.cache:/home/jovyan/.cache
      - ./.jupyter:/home/jovyan/.jupyter
      - conda_envs:/opt/conda/
    command: start-notebook.py --NotebookApp.token='changethis'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  conda_envs:
    driver: local
