services:
  jupyter1:
    restart: always
    build:
      context: .
    ports:
      - 8888:8888
    volumes:
      - ~/projects:/home/jovyan/projects
      - ./.jupyter:/home/jovyan/.jupyter
      - ~/.cache:/home/jovyan/.cache
      - conda_envs:/opt/conda/
    command: start-notebook.py --NotebookApp.token="${JUPYTER_TOKEN}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # jupyter2:
  #   restart: always
  #   build:
  #     context: .
  #   ports:
  #     - 8887:8888
  #   volumes:
  #     - ~/projects:/home/jovyan/projects
  #     - ./.jupyter2:/home/jovyan/.jupyter
  #     - ~/.cache:/home/jovyan/.cache
  #     - conda_envs2:/opt/conda/
  #   command: start-notebook.py --NotebookApp.token="${JUPYTER_TOKEN}"
  #

volumes:
  conda_envs:
    driver: local
  # conda_envs2:
  #   driver: local
